### ISSUE TITLE
Quick Question.

### ISSUE THREAD

**Issue by 33nanoseconds** [naveenjujaray/DeveloperFolio#3]
I cloned the project in Visual Studio and one thing puzzled me. Why is the code in the welcomepagemain.dart (Rows folder) repeated 3 times?  
* Without the repetition its only 179 lines of code
* With the repetition its 710 lines of code. 
  
Side Note: I am still learning and i figured the best way to learn is look at other peoples code. I am just surprised that you repeat your code. Is that possibly unique to flutter web?

**Comment by naveenjujaray** [comment]
I've used responsive_builder plugin which requires 3 screentype layouts such as Desktop layout, Tablet Layout, Mobile Layout & it even supports Landscape Layout too. So to answer your question this is the reason I've repeated the code 3 times for compatability for different layouts.

**Comment by 33nanoseconds** [comment]
Thanks, that makes a lot of sense.
